version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - spongemock:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ./images:/app/images
    expose:
      - "5000"
    ports:
      - 5000:5000
