apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spongemock-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
